on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Install Zola'
        run: sudo snap install --edge zola
      - name: 'Build Zola site'
        run: zola build
